module huffmancodes

/// http://http2.github.io/http2-spec/compression.html#huffman.code
/// Array of the huffman encoding table. Index in the array corresponds to the byte value it represents, with the last value being the EOS identifier
let table = [|
    [|true; true; true; true; true; true; true; true; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true|];
    [|false; true; false; true; false; false|];
    [|true; true; true; true; true; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; false; false; true|];
    [|false; true; false; true; false; true|];
    [|true; true; true; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; false; true; true|];
    [|true; true; true; true; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; false; true; true|];
    [|true; true; true; true; true; false; true; false|];
    [|false; true; false; true; true; false|];
    [|false; true; false; true; true; true|];
    [|false; true; true; false; false; false|];
    [|false; false; false; false; false|];
    [|false; false; false; false; true|];
    [|false; false; false; true; false|];
    [|false; true; true; false; false; true|];
    [|false; true; true; false; true; false|];
    [|false; true; true; false; true; true|];
    [|false; true; true; true; false; false|];
    [|false; true; true; true; false; true|];
    [|false; true; true; true; true; false|];
    [|false; true; true; true; true; true|];
    [|true; false; true; true; true; false; false|];
    [|true; true; true; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; false; false|];
    [|true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; false; true; false|];
    [|true; false; false; false; false; true|];
    [|true; false; true; true; true; false; true|];
    [|true; false; true; true; true; true; false|];
    [|true; false; true; true; true; true; true|];
    [|true; true; false; false; false; false; false|];
    [|true; true; false; false; false; false; true|];
    [|true; true; false; false; false; true; false|];
    [|true; true; false; false; false; true; true|];
    [|true; true; false; false; true; false; false|];
    [|true; true; false; false; true; false; true|];
    [|true; true; false; false; true; true; false|];
    [|true; true; false; false; true; true; true|];
    [|true; true; false; true; false; false; false|];
    [|true; true; false; true; false; false; true|];
    [|true; true; false; true; false; true; false|];
    [|true; true; false; true; false; true; true|];
    [|true; true; false; true; true; false; false|];
    [|true; true; false; true; true; false; true|];
    [|true; true; false; true; true; true; false|];
    [|true; true; false; true; true; true; true|];
    [|true; true; true; false; false; false; false|];
    [|true; true; true; false; false; false; true|];
    [|true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; false; false|];
    [|true; true; true; false; false; true; true|];
    [|true; true; true; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; false; false|];
    [|true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; false; true|];
    [|false; false; false; true; true|];
    [|true; false; false; false; true; true|];
    [|false; false; true; false; false|];
    [|true; false; false; true; false; false|];
    [|false; false; true; false; true|];
    [|true; false; false; true; false; true|];
    [|true; false; false; true; true; false|];
    [|true; false; false; true; true; true|];
    [|false; false; true; true; false|];
    [|true; true; true; false; true; false; false|];
    [|true; true; true; false; true; false; true|];
    [|true; false; true; false; false; false|];
    [|true; false; true; false; false; true|];
    [|true; false; true; false; true; false|];
    [|false; false; true; true; true|];
    [|true; false; true; false; true; true|];
    [|true; true; true; false; true; true; false|];
    [|true; false; true; true; false; false|];
    [|false; true; false; false; false|];
    [|false; true; false; false; true|];
    [|true; false; true; true; false; true|];
    [|true; true; true; false; true; true; true|];
    [|true; true; true; true; false; false; false|];
    [|true; true; true; true; false; false; true|];
    [|true; true; true; true; false; true; false|];
    [|true; true; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; false; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; false; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; true|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; false; false; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; false; true; true; true; false|];
    [|true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true; true|]
|]

